import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Impact and scale", description: "Explore StoryBridge Legacy’s proposed path from a carefully governed pilot to Caribbean and global diaspora connection." };

const roadmap = [
  { stage: "Stage 1", title: "Proposed CIC pilot", text: "Validate archive contribution and moderation, gather alumni and student feedback, and confirm governance, permissions and safeguarding." },
  { stage: "Stage 2", title: "Trinidad and Tobago rollout", text: "Offer future branded institutional spaces, support secondary schools and youth institutions, and develop national alumni connections." },
  { stage: "Stage 3", title: "Caribbean expansion", text: "Connect participating institutions, share implementation standards, and support regional mentorship and opportunity networks." },
  { stage: "Stage 4", title: "Global diaspora network", text: "Engage Caribbean alumni across North America, the United Kingdom, Europe and elsewhere through intergenerational professional and philanthropic connections." },
];

const safeguards = ["Institutional permission", "Human moderation", "Historical verification", "Contributor consent", "Student privacy", "Future role-based access", "Public/private information boundaries", "Responsible AI use", "No automated publication", "No guaranteed fundraising or investment outcomes"];

export default function ImpactPage() {
  return (
    <>
      <header className="page-hero impact-hero"><div className="shell narrow-shell"><p className="eyebrow">Impact and scale</p><h1>Shared history can become infrastructure for connection.</h1><p className="lede">The long-term vision is a global intergenerational Caribbean network where institutional memory becomes a bridge to mentorship, knowledge, philanthropy and opportunity—without overstating what technology alone can achieve.</p><div className="demo-notice" role="note"><strong>Future vision, not completed deployment.</strong> CIC/St. Mary’s College is a proposed pilot only. No formal endorsement, national rollout, regional launch, partner commitment or funding is claimed.</div></div></header>

      <section className="section impact-challenge"><div className="shell split-section"><div><p className="eyebrow">01 · The challenge</p><h2>Connections are valuable, but often fragmented.</h2></div><div className="prose-stack"><p>Caribbean schools may hold photographs, memories and records across cupboards, personal collections and informal groups. Alumni relationships can depend on individual volunteers, while migration may weaken direct access to expertise, professional networks and resources.</p><p>Students in developing countries can face narrower access to mentorship, internships, professional networks and investment ecosystems. Caribbean institutions are not helpless or inferior: they hold deep knowledge, capable communities and strong identities. The gap is often one of organised connection and access.</p><p>Technology can support that work, but it cannot solve structural inequality, brain drain or safeguarding by itself.</p></div></div></section>

      <section className="impact-circulation"><div className="shell"><div className="section-heading-row"><div><p className="eyebrow">02 · Brain circulation</p><h2>Keep knowledge moving in every direction.</h2></div><p>Local alumni remain equally important. The goal is not to celebrate departure or portray migration as betrayal, but to reconnect people across geography and generations.</p></div><div className="impact-opportunity-grid"><article><h3>Share expertise</h3><p>Mentorship, career guidance, virtual sessions, portfolio review and entrepreneurship advice.</p></article><article><h3>Create access</h3><p>Internships, professional networks, international introductions and employment pathways without guaranteed placement.</p></article><article><h3>Strengthen programmes</h3><p>Scholarships, equipment, club support, fundraising readiness and professional services.</p></article><article><h3>Build responsible connections</h3><p>Future responsible investment introductions and institutional partnerships—not an investment marketplace.</p></article></div></div></section>

      <section className="section impact-engagement"><div className="shell split-section"><div><p className="eyebrow">03 · Engagement and fundraising</p><h2>Identity can renew the reason to participate.</h2></div><div className="prose-stack"><p>Stories help alumni remember who shaped them and why an institution still matters. Once engagement is restored, schools can build more meaningful pathways for alumni giving, scholarships, club sponsorship, equipment support, capital projects, diaspora philanthropy, professional services, partnerships and future fundraising campaigns.</p><p>This MVP does not process donations, display donation totals or claim confirmed campaigns. Any future fundraising would require institutional approval, financial controls and transparent reporting.</p></div></div></section>

      <section className="impact-investment"><div className="shell split-section"><div><p className="eyebrow">04 · Investment and opportunity</p><h2>Connection before capital.</h2></div><div className="prose-stack"><p>Reconnected alumni may eventually help young people through youth-enterprise mentorship, business-concept review, entrepreneurship guidance, professional connections, internships, employment access, institutional partnerships and responsible investor introductions.</p><p>StoryBridge Legacy does not promise funding or returns, promote investments to minors, execute transactions or operate as an investment marketplace. These are future opportunity pathways that would require separate governance, professional review and safeguarding.</p></div></div></section>

      <section className="section roadmap-section"><div className="shell"><div className="section-heading-row"><div><p className="eyebrow">05 · Scale roadmap</p><h2>Grow only after learning and permission.</h2></div><p>Every stage below is a future plan. Progress depends on evidence, governance, community feedback, institutional consent and appropriate resources.</p></div><ol className="roadmap-list">{roadmap.map((item) => <li key={item.stage}><span>{item.stage}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></li>)}</ol></div></section>

      <section className="sustainability-section"><div className="shell split-section"><div><p className="eyebrow">06 · Sustainability</p><h2>Several routes, no premature commitment.</h2></div><div><p>Possible future sustainability routes include institutional subscriptions, sponsored school access, foundation and grant support, alumni-association partnerships, corporate social responsibility sponsorship, digitisation and archive services, and training and implementation support.</p><p>No prices, confirmed funders or final business model are presented in this MVP.</p></div></div></section>

      <section className="section safeguards-section"><div className="shell"><div className="section-heading-row"><div><p className="eyebrow">07 · Safeguards</p><h2>Trust must scale with the network.</h2></div><p>Growth without permission, privacy and human responsibility would undermine the archive and the relationships it hopes to strengthen.</p></div><ul className="safeguard-grid">{safeguards.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ul></div></section>

      <section className="impact-closing"><div className="shell closing-grid"><div><p className="eyebrow">08 · Closing vision</p><h2>Our history can be a bridge to shared opportunity.</h2><p>The long-term vision is a global intergenerational Caribbean network where shared history becomes a bridge to mentorship, funding, knowledge and opportunity—supported by consent, governance and credible human relationships.</p></div><div className="actions"><Link className="button light-button" href="/legacy">Explore the Legacy</Link><Link className="button outline-light" href="/contribute">Share a Story</Link><Link className="button outline-light" href="/alumni">Join the Alumni Network</Link><Link className="button outline-light" href="/engage">Offer Support</Link></div></div></section>
    </>
  );
}
